# Generated by Django 5.2.4 on 2025-08-25 08:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0001_initial"),
        ("users", "0002_alter_organization_options_alter_organization_table"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="target",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                models.F("organization"),
                name="uq_targets_org_email_ci",
            ),
        ),
    ]
