# Generated by Django 5.2.4 on 2025-08-12 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('targets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_queue', to='campaigns.campaign')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_emails', to='targets.target')),
            ],
            options={
                'db_table': 'email_queue',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_limit', models.IntegerField(default=1000)),
                ('current_daily_count', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_configs', to='users.organization')),
            ],
            options={
                'db_table': 'smtp_configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('sent', 'Email Sent'), ('delivered', 'Email Delivered'), ('bounced', 'Email Bounced'), ('opened', 'Email Opened'), ('clicked', 'Link Clicked'), ('reported', 'Reported as Spam/Phishing')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('bounce_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='campaigns.campaign')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='targets.target')),
            ],
            options={
                'db_table': 'email_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['campaign', 'event_type'], name='email_event_campaig_9b82e7_idx'), models.Index(fields=['target', 'timestamp'], name='email_event_target__f6d412_idx')],
            },
        ),
    ]
