# Generated by Django 5.2.4 on 2025-08-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
    ]
