# Generated by Django 5.2.4 on 2025-08-12 10:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_emails', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_delivered', models.IntegerField(default=0)),
                ('emails_bounced', models.IntegerField(default=0)),
                ('emails_opened', models.IntegerField(default=0)),
                ('emails_clicked', models.IntegerField(default=0)),
                ('page_visits', models.IntegerField(default=0)),
                ('credentials_captured', models.IntegerField(default=0)),
                ('data_submitted', models.IntegerField(default=0)),
                ('emails_reported', models.IntegerField(default=0)),
                ('delivery_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('open_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('click_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('click_through_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('susceptibility_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('awareness_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_reports',
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('campaign_summary', 'Campaign Summary'), ('security_metrics', 'Security Metrics'), ('department_breakdown', 'Department Breakdown'), ('trend_analysis', 'Trend Analysis'), ('executive_summary', 'Executive Summary')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('include_campaigns', models.ManyToManyField(blank=True, related_name='scheduled_reports', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='users.organization')),
            ],
            options={
                'db_table': 'scheduled_reports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('total_employees', models.IntegerField()),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_opened', models.IntegerField(default=0)),
                ('links_clicked', models.IntegerField(default=0)),
                ('data_submitted', models.IntegerField(default=0)),
                ('emails_reported', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('improvement_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_reports', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_reports', to='users.organization')),
            ],
            options={
                'db_table': 'department_reports',
                'ordering': ['department'],
                'unique_together': {('campaign', 'department')},
            },
        ),
    ]
