# Generated by Django 5.2.4 on 2025-08-11 10:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('social_media', 'Social Media'), ('it_support', 'IT Support'), ('hr_notice', 'HR Notice'), ('security_alert', 'Security Alert'), ('invoice', 'Invoice/Payment'), ('shipping', 'Shipping Notification'), ('banking', 'Banking Alert'), ('custom', 'Custom')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='users.organization')),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('css_content', models.TextField(blank=True)),
                ('redirect_url', models.URLField(blank=True)),
                ('page_type', models.CharField(choices=[('login', 'Login Page'), ('survey', 'Survey Form'), ('download', 'File Download'), ('notification', 'Notification Page'), ('banking', 'Banking Portal'), ('social', 'Social Media'), ('custom', 'Custom Page')], max_length=50)),
                ('capture_credentials', models.BooleanField(default=True)),
                ('capture_form_data', models.BooleanField(default=True)),
                ('show_awareness_message', models.BooleanField(default=True)),
                ('awareness_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='users.organization')),
            ],
            options={
                'db_table': 'landing_pages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('send_interval_minutes', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('capture_credentials', models.BooleanField(default=True)),
                ('capture_data', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('individual_targets', models.ManyToManyField(blank=True, related_name='individual_campaigns', to='targets.target')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='users.organization')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='campaigns', to='targets.targetgroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.emailtemplate')),
                ('landing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.landingpage')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Email Sent'), ('opened', 'Email Opened'), ('clicked', 'Link Clicked'), ('submitted', 'Data Submitted'), ('reported', 'Reported as Phishing'), ('failed', 'Failed to Send')], default='pending', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('link_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('data_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='campaigns.campaign')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='targets.target')),
            ],
            options={
                'db_table': 'campaign_targets',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'target')},
            },
        ),
    ]
