# Generated by Django 5.2.4 on 2025-08-12 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('targets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('click_rate_threshold', 'Click Rate Threshold'), ('multiple_clicks_same_ip', 'Multiple Clicks Same IP'), ('credential_submission', 'Credential Submission'), ('campaign_completion', 'Campaign Completion'), ('failed_email_threshold', 'Failed Email Threshold'), ('high_risk_user_click', 'High Risk User Click')], max_length=50)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('time_window_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('notify_users', models.ManyToManyField(related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='users.organization')),
            ],
            options={
                'db_table': 'alert_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_campaign_updates', models.BooleanField(default=True)),
                ('email_security_alerts', models.BooleanField(default=True)),
                ('email_reports', models.BooleanField(default=True)),
                ('email_billing', models.BooleanField(default=True)),
                ('app_campaign_updates', models.BooleanField(default=True)),
                ('app_security_alerts', models.BooleanField(default=True)),
                ('app_system_alerts', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('disabled', 'Disabled')], default='realtime', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('campaign_started', 'Campaign Started'), ('campaign_completed', 'Campaign Completed'), ('high_risk_click', 'High Risk Click Detected'), ('security_breach', 'Potential Security Breach'), ('report_ready', 'Report Ready'), ('system_alert', 'System Alert'), ('billing_alert', 'Billing Alert'), ('training_reminder', 'Training Reminder')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='campaigns.campaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='targets.target')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
